package main.java.org.algodsa;

/**
 * The {@code FindTheDifference} class provides a method to find the extra character
 * in string {@code t} which is not present in string {@code s}.
 * <br>
 * It is assumed that {@code t} is generated by shuffling {@code s} and adding one extra character.
 */
public class FindTheDifference {

    /**
     * Default constructor for the FindTheDifference class.
     * This constructor initializes the FindTheDifference class.
     */
    public FindTheDifference() {}

    /**
     * <h4><a href="https://leetcode.com/problems/find-the-difference/">389. Find the Difference</a></h4>
     * <br>
     * Finds the character that was added to {@code t}.
     *  <br>
     * Time Complexity: O(n)
     *  - Where n is the length of string {@code s}. Both strings are traversed once.
     *  <br>
     * Space Complexity: O(1)
     *  - A fixed-size array of length 26 is used for counting characters.
     * <br><br>
     * @param s the original string
     * @param t the modified string with one additional character
     * @return the character that was added to {@code t}
     */
    public char findTheDifference(String s, String t) {
        int[] count = new int[26];

        for (char c : s.toCharArray()) count[c - 'a']++;
        for (char c : t.toCharArray()) {
            if (--count[c - 'a'] < 0) return c;
        }

        return '?'; // shouldn't reach here if inputs are valid
    }
}
