# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Java Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests in Java Directory
    runs-on: ubuntu-latest

    steps:
      # Checkout the code in your repository
    - name: Checkout code
      uses: actions/checkout@v3

      # Set up the JDK environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        
    # Navigate to the java directory and run Maven tests
    - name: Run Maven tests
      run: |
        cd java
        mvn test
